name: epson_epos_printer
description: A new flutter plugin project.
version: 0.0.1
homepage: https://github.com/timnew/epson_epos_printer

environment:
  sdk: '>=2.16.1 <3.0.0'
  flutter: '>=2.5.0'

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  logging: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.8.2
  freezed: ^1.1.1
  build_runner: ^2.1.8
  json_serializable: ^6.1.6

flutter:
  plugin:
    platforms:
      android:
        enabled: false # NOT YET SUPPORTED
      #   package: me.timnew.epson_epos_printer
      #   pluginClass: EpsonEposPrinterPlugin
      ios:
        pluginClass: EpsonEposPrinterPlugin
